### ISSUE TITLE
Any plans to update the software?

### ISSUE THREAD

**Issue by arthurlyk** [dvgamerr-app/hentai-downloader#88]
It doesn't work anymore, it used to be the best app for e-hentai

**Comment by dvgamerr** [comment]
Many libraries have discontinued support over time and  unable to fix past bugs, so I'm starting to create new ones.

![image](https://github.com/dvgamerr-app/hentai-downloader/assets/10203425/2c48c0ee-2ca6-47c4-99bb-eede80e63735)
